=== AlehMeshchanka/JD2017-09-20/src/by/it/shelkovich/jd2_07/dtd/data.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT payment (payer, order)>
        <!ELEMENT payer (name, email)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT order (date, shippingPrice, products)>
        <!ATTLIST order
                id CDATA #REQUIRED
                >
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT shippingPrice (#PCDATA)>
        <!ELEMENT products (product)+>
        <!ELEMENT product (productName, price)>
        <!ELEMENT productName (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== AlehMeshchanka/JD2017-09-20/src/by/it/shelkovich/jd2_07/dtd/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE payment SYSTEM "data.dtd" >
<payment>
    <payer>
        <name>Alexander Druz</name>
        <email>druz@chtogdekogda.ru</email>
    </payer>
    <order id="4519">
        <date>1510997912231</date>
        <shippingPrice>200</shippingPrice>
        <products>
            <product>
                <productName>Baraban</productName>
                <price>6000</price>
            </product>
            <product>
                <productName>Volchok</productName>
                <price>1000</price>
            </product>
        </products>
    </order>
</payment>
