<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ShoppingCenters [
    <!ELEMENT ShoppingCenters (ShoppingCenter)+>
    <!ELEMENT ShoppingCenter (Name, Adress, Lat, Lng, Rooms)>
    <!ELEMENT Name (#PCDATA)>
    <!ELEMENT Adress (#PCDATA)>
    <!ELEMENT Lat (#PCDATA)>
    <!ELEMENT Lng (#PCDATA)>
    <!ELEMENT Rooms (Room)+>
    <!ELEMENT Room (RoomName, Square, Price, isRented) >
    <!ELEMENT RoomName (#PCDATA)>
    <!ELEMENT Square (#PCDATA)>
    <!ELEMENT Price (#PCDATA)>
    <!ELEMENT isRented (#PCDATA)>
]>
<ShoppingCenters>
    <ShoppingCenter>
        <Name>Korona</Name>
        <Adress>Minsk, str.Pobeditelei 65</Adress>
        <Lat>51.3</Lat>
        <Lng>23.6</Lng>
        <Rooms>
            <Room>
                <RoomName>B147</RoomName>
                <Square>150.4</Square>
                <Price>900</Price>
                <isRented>false</isRented>
            </Room>
        </Rooms>
    </ShoppingCenter>
</ShoppingCenters>