<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Persons[
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Nickname, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Description, Address, Floor, Floors, Square, Price)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Square (#PCDATA)>
        <!ELEMENT Price (#PCDATA)>]>
<Persons>
    <Person>
        <Email>asd@asd.com</Email>
        <Nickname>asd123</Nickname>
        <Password>qwerty</Password>
        <Ads>
            <Ad>
                <Description>Nice variant</Description>
                <Address>Minsk, Lenina 24-5 str.</Address>
                <Floor>3</Floor>
                <Floors>5</Floors>
                <Square>49.0</Square>
                <Price>567.0</Price>
            </Ad>
        </Ads>
    </Person>
</Persons>