=== AlehMeshchanka/JD2017-09-20/src/by/it/meshchenko/jd02_07/xsd/Persons.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.it.meshchenko/Persons"
        xmlns:tns="http://by.it.meshchenko/Persons"
        elementFormDefault="qualified">
    <element name="Persons">
        <complexType>
            <sequence>
                <element name="Person" type="tns:Person" maxOccurs="unbounded"></element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Email" type="string"></element>
            <element name="Nickname" type="string"></element>
            <element name="Password" type="string"></element>
            <element name="Ads" type="tns:Ads"></element>
        </sequence>
    </complexType>
    <complexType name="Ads">
        <sequence>
            <element name="Ad" type="tns:Ad"></element>
        </sequence>
    </complexType>
    <complexType name="Ad">
        <all>
            <element name="Description" type="string"></element>
            <element name="Count" type="string"></element>
            <element name="Square" type="string"></element>
        </all>
    </complexType>
</schema>

=== AlehMeshchanka/JD2017-09-20/src/by/it/meshchenko/jd02_07/xsd/personsForXSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://by.it.meshchenko/Persons Persons.xsd"
            xmlns="http://by.it.meshchenko/Persons"
>
    <Person>
        <Email>asd@aasd.it</Email>
        <Nickname>qwerty</Nickname>
        <Password>123</Password>
        <Ads>
            <Ad>
                <Description>GOOD</Description>
                <Count>555</Count>
                <Square>50</Square>
            </Ad>
        </Ads>
    </Person>
</Persons>
