=== AlehMeshchanka/JD2017-09-20/src/by/it/meshchenko/jd02_07/ShoppingCenters.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.it.meshchenko/ShoppingCenters"
        xmlns:tns="http://by.it.meshchenko/ShoppingCenters"
        elementFormDefault="qualified">
    <element name="ShoppingCenters">
        <complexType>
            <sequence>
                <element
                        name="ShoppingCenter"
                        type="tns:ShoppingCenter"
                        maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="ShoppingCenter">
        <sequence>
            <element name="Name" type="string" />
            <element name="Adress" type="string" />
            <element name="Lat" type="string" />
            <element name="Lng" type="string" />
            <element name="Rooms" type="tns:Rooms" />
        </sequence>
    </complexType>
    <complexType name="Rooms">
        <sequence>
            <element name="Room" type="tns:Room" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <complexType name="Room">
        <all>
            <element name="RoomName" type="string" />
            <element name="Square" type="string" />
            <element name="Price" type="string" />
            <element name="isRented" type="boolean" />
        </all>
    </complexType>
</schema>

=== AlehMeshchanka/JD2017-09-20/src/by/it/meshchenko/jd02_07/ShoppingCenters.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ShoppingCenters xmlns="http://by.it.meshchenko/ShoppingCenters"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://by.it.meshchenko/ShoppingCenters ShoppingCenters.xsd"

>
    <ShoppingCenter>
        <Name>Korona</Name>
        <Adress>Minsk, str.Pobeditelei 65</Adress>
        <Lat>51.3</Lat>
        <Lng>23.6</Lng>
        <Rooms>
            <Room>
                <RoomName>B147</RoomName>
                <Square>150.4</Square>
                <Price>900</Price>
                <isRented>false</isRented>
            </Room>
        </Rooms>
    </ShoppingCenter>
</ShoppingCenters>
