<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE users[
<!ELEMENT users (user)+>
<!ELEMENT user (name, nick, telephone, adres,ads) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT nick (#PCDATA) >
<!ELEMENT telephone (#PCDATA) >
<!ELEMENT adres (country,city) >
<!ELEMENT country (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT ads (ad)+>
<!ELEMENT ad (processor, video_card, motherboard, ram, power_supply, HDD) >
<!ELEMENT processor (#PCDATA) >
<!ELEMENT video_card (#PCDATA) >
<!ELEMENT motherboard (#PCDATA) >
<!ELEMENT ram (#PCDATA) >
<!ELEMENT power_supply (#PCDATA) >
<!ELEMENT HDD (#PCDATA) >
]>
        <users>
        <user>
        <name>Govor Eugene </name>
        <nick> ...</nick>
        <telephone>+375447771060</telephone>
        <adres>
        <country>Belarus</country>
        <city>Minsk</city>
        </adres>
        <ads>
        <ad>
        <processor> Ryzen 5 1600</processor>
        <video_card> NVIDIA GeForce GTX 1060</video_card>
        <motherboard>B350</motherboard>
        <ram> 16Gb 3.2</ram>
        <power_supply> ... 5000W</power_supply>
        <HDD>...</HDD>
        </ad>
        </ads>
        </user>
        </users>