=== AlehMeshchanka/JD2017-09-20/src/by/it/malyshev/jd02_07/Gendata.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://by.it.malyshev/jd02_07/Gendata"
        xmlns:xsi="http://by.it.malyshev/jd02_07/Gendata"
        elementFormDefault="qualified">
    <element name="Gendata">
        <complexType>
            <sequence>
                <element name="Person"
                         type="xsi:Person"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="Person">
        <sequence>
            <element name="Name" type="string"/>
            <element name="Ancestor" type="string"/>
            <element name="Country" type="string"/>
            <element name="Geocoord" type="xsi:Geocoord"/>
            <element name="Haplotype" type="xsi:Haplotype"/>
        </sequence>
        <attribute name="kit" type="string" use="required"/>
    </complexType>

    <complexType name="Geocoord">
        <sequence>
            <element name="Latitude" type="double"/>
            <element name="Longitude" type="double"/>
        </sequence>
    </complexType>

    <complexType name="Haplotype">
        <sequence>
            <element name="STRmarkers" type="xsi:STRmarkers"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="STRmarkers">
        <sequence>
            <element name="DYS393" type="positiveInteger"/>
            <element name="DYS390" type="positiveInteger"/>
            <element name="DYS19" type="positiveInteger"/>
            <element name="DYS391" type="positiveInteger"/>
            <element name="DYS385a" type="positiveInteger"/>
            <element name="DYS385b" type="positiveInteger"/>
            <element name="DYS426" type="positiveInteger"/>
            <element name="DYS388" type="positiveInteger"/>
            <element name="DYS439" type="positiveInteger"/>
            <element name="DYS389i" type="positiveInteger"/>
            <element name="DYS392" type="positiveInteger"/>
            <element name="DYS389ii" type="positiveInteger"/>
        </sequence>
    </complexType>
</schema>

=== AlehMeshchanka/JD2017-09-20/src/by/it/malyshev/jd02_07/Gendata+XSD.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Gendata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://by/it/malyshev/jd02_07/gendata Gendata.xsd"
         xmlns="http://by/it/malyshev/jd02_07/gendata"
>
    <Person kit="N22223">
        <Name>Archibald Volf</Name>
        <Ancestor>Adam Volf</Ancestor>
        <Country>Switzerland</Country>
        <Geocoord>
            <Latitude>46.9983</Latitude>
            <Longitude>7.4513</Longitude>
        </Geocoord>
        <Haplotype>
            <STRmarkers>
                <DYS393>12</DYS393>
                <DYS390>24</DYS390>
                <DYS19>14</DYS19>
                <DYS391>12</DYS391>
                <DYS385a>12</DYS385a>
                <DYS385b>15</DYS385b>
                <DYS426>12</DYS426>
                <DYS388>12</DYS388>
                <DYS439>13</DYS439>
                <DYS389i>14</DYS389i>
                <DYS392>13</DYS392>
                <DYS389ii>30</DYS389ii>
            </STRmarkers>
        </Haplotype>
    </Person>
</Gendata>
