<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Gendata [
        <!ELEMENT Gendata (Person)+>
        <!ELEMENT Person (Name, Ancestor, Country, Geocoord, Haplotype)>
        <!ATTLIST Person kit CDATA #REQUIRED>
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Ancestor (#PCDATA)>
        <!ELEMENT Country (#PCDATA)>
        <!ELEMENT Geocoord (Latitude, Longitude)>
        <!ELEMENT Latitude (#PCDATA)>
        <!ELEMENT Longitude (#PCDATA)>
        <!ELEMENT Haplotype (STRmarkers)+>
        <!ELEMENT STRmarkers (DYS393,DYS390,DYS19,DYS391,DYS385a,DYS385b,DYS426,DYS388,DYS439,DYS389i,DYS392,DYS389ii)>
        <!ELEMENT DYS393 (#PCDATA)>
        <!ELEMENT DYS390 (#PCDATA)>
        <!ELEMENT DYS19 (#PCDATA)>
        <!ELEMENT DYS391 (#PCDATA)>
        <!ELEMENT DYS385a (#PCDATA)>
        <!ELEMENT DYS385b (#PCDATA)>
        <!ELEMENT DYS426 (#PCDATA)>
        <!ELEMENT DYS388 (#PCDATA)>
        <!ELEMENT DYS439 (#PCDATA)>
        <!ELEMENT DYS389i (#PCDATA)>
        <!ELEMENT DYS392 (#PCDATA)>
        <!ELEMENT DYS389ii (#PCDATA)>
        ]>
<Gendata>
    <Person kit="N22223">
        <Name>Archibald Volf</Name>
        <Ancestor>Adam Volf</Ancestor>
        <Country>Switzerland</Country>
        <Geocoord>
            <Latitude>46.9983</Latitude>
            <Longitude>7.4513</Longitude>
        </Geocoord>
        <Haplotype>
            <STRmarkers>
                <DYS393>12</DYS393>
                <DYS390>24</DYS390>
                <DYS19>14</DYS19>
                <DYS391>12</DYS391>
                <DYS385a>12</DYS385a>
                <DYS385b>15</DYS385b>
                <DYS426>12</DYS426>
                <DYS388>12</DYS388>
                <DYS439>13</DYS439>
                <DYS389i>14</DYS389i>
                <DYS392>13</DYS392>
                <DYS389ii>30</DYS389ii>
            </STRmarkers>
        </Haplotype>
    </Person>
</Gendata>