=== AlehMeshchanka/JD2017-09-20/src/by/it/shelkovich/jd2_09/data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd2_09.shelkovich.it.by"
        xmlns:tns="http://jd2_09.shelkovich.it.by"
        elementFormDefault="qualified">

    <element name="payment">
        <complexType>
            <sequence>
                <element name="payer">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="email" type="string"/>
                        </sequence>
                    </complexType>
                </element>
                <element name="order" type="tns:order" />
            </sequence>

        </complexType>
    </element>

    <complexType name="order">
        <sequence>
            <element name="date" type="long"/>
            <element name="shippingPrice" type="integer"/>
            <element name="products">
                <complexType>
                    <sequence>
                        <element name="product" maxOccurs="unbounded">
                            <complexType>
                                <sequence>
                                    <element name="productName" type="string"/>
                                    <element name="price" type="integer"/>
                                </sequence>
                            </complexType>
                        </element>
                    </sequence>
                </complexType>
            </element>
        </sequence>
        <attribute name="id" type="integer" use="required"/>
    </complexType>


</schema>

=== AlehMeshchanka/JD2017-09-20/src/by/it/shelkovich/jd2_10/bean/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<payment
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://jd2_09.shelkovich.it.by data.xsd"
        xmlns="http://jd2_09.shelkovich.it.by"
>
    <payer>
        <name>Alexander Druz</name>
        <email>druz@chtogdekogda.ru</email>
    </payer>
    <order id="4519">
        <date>1510997912231</date>
        <shippingPrice>200</shippingPrice>
        <products>
            <product>
                <productName>Baraban&amp;"MM's</productName>
                <price>6000</price>
            </product>
            <product>
                <productName>Volchok</productName>
                <price>1000</price>
            </product>
        </products>
    </order>
</payment>

=== AlehMeshchanka/JD2017-09-20/src/by/it/shelkovich/jd2_08/xsd/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<payment
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://by.it.shelkovich/payment data.xsd"
        xmlns="http://by.it.shelkovich/payment"
>
    <payer>
        <name>Alexander Druz</name>
        <email>druz@chtogdekogda.ru</email>
    </payer>
    <order id="4519">
        <date>1510997912231</date>
        <shippingPrice>200</shippingPrice>
        <products>
            <product>
                <productName>Baraban&amp;"MM's</productName>
                <price>6000</price>
            </product>
            <product>
                <productName>Volchok</productName>
                <price>1000</price>
            </product>
        </products>
    </order>
</payment>
