<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE Persons [
        <!ELEMENT Persons (Person)+ >
        <!ELEMENT Person (Email, Nickname, Password, Ads) >
        <!ELEMENT Email (#PCDATA) >
        <!ELEMENT Nickname (#PCDATA) >
        <!ELEMENT Password (#PCDATA) >
        <!ELEMENT Ads (Ad)+ >
        <!ELEMENT Ad (Description, Count, Square) >
        <!ATTLIST Ad Price CDATA #REQUIRED>
        <!ELEMENT Description (#PCDATA) >
        <!ELEMENT Count (#PCDATA) >
        <!ELEMENT Square (#PCDATA) >
]>
<Persons>
    <Person>
        <Email>asd@aasd.it</Email>
        <Nickname>qwerty</Nickname>
        <Password>123</Password>
        <Ads>
            <Ad Price="48500.00">
                <Description>GOOD</Description>
                <Count>555</Count>
                <Square>50</Square>
            </Ad>
        </Ads>
    </Person>
</Persons>