=== AlehMeshchanka/JD2017-09-20/src/by/it/govor/jd02_09/XML.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="jd02_09.govor.it.by"
        xmlns:tns="jd02_09.govor.it.by"
        elementFormDefault="qualified">
    <element name="users">
        <complexType>
            <sequence>
                <element name="user"
                         type="tns:user"
                         maxOccurs="unbounded">
                </element>
            </sequence>
        </complexType>
    </element>
    <complexType name="user">
        <sequence>
            <element name="name" type="string" />
            <element name="nick" type="string" />
            <element name="telephone" type="string" />
            <element name="adres" type="tns:adres" />
            <element name="ads" type="tns:ads" />
        </sequence>
    </complexType>

    <complexType name="adres">
        <sequence>
            <element name="country" type="string"/>
            <element name="city" type="string"/>
        </sequence>
    </complexType>

    <complexType name="ads">
        <sequence>
            <element name="ad" type="tns:ad"
                     minOccurs="1"
                     maxOccurs="unbounded">
            </element>
        </sequence>
    </complexType>

    <complexType name="ad">
        <all>
            <element name="processor" type="string" />
            <element name="video_card" type="string" />
            <element name="motherboard" type="string" />
            <element name="ram" type="string" />
            <element name="power_supply" type="string" />
            <element name="HDD" type="string" />
        </all>
    </complexType>
</schema>

=== AlehMeshchanka/JD2017-09-20/src/by/it/govor/jd02_09/XML_xsd.xml
<?xml version="1.0" encoding ="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://jd02_09.govor.it.by XML.xsd"
         xmlns="jd02_09.govor.it.by"
>
    <user>
        <name>Govor Eugene </name>
        <nick> ...</nick>
        <telephone>+375447771060</telephone>
        <adres>
            <country>Belarus</country>
            <city>Minsk</city>
        </adres>
        <ads>
            <ad>
                <processor> Ryzen 5 1600</processor>
                <video_card> NVIDIA GeForce GTX 1060</video_card>
                <motherboard>B350</motherboard>
                <ram> 16Gb 3.2</ram>
                <power_supply> ... 5000W</power_supply>
                <HDD>...</HDD>
            </ad>
        </ads>
    </user>
    </users>

=== AlehMeshchanka/JD2017-09-20/src/by/it/govor/jd02_07/XML_xsd.xml
<?xml version="1.0" encoding ="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://by.it.govor/XML XML.xsd"
         xmlns="http://by.it.govor/XML"
>
    <user>
        <name>Govor Eugene </name>
        <nick> ...</nick>
        <telephone>+375447771060</telephone>
        <adres>
            <country>Belarus</country>
            <city>Minsk</city>
        </adres>
        <ads>
            <ad>
                <processor> Ryzen 5 1600</processor>
                <video_card> NVIDIA GeForce GTX 1060</video_card>
                <motherboard>B350</motherboard>
                <ram> 16Gb 3.2</ram>
                <power_supply> ... 5000W</power_supply>
                <HDD>...</HDD>
            </ad>
        </ads>
    </user>
    </users>
