<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE Students[
        <!ELEMENT Students (Student)+>
        <!ELEMENT Student (Name, Surname, Email, Subjects) >
        <!ELEMENT Name (#PCDATA)>
        <!ELEMENT Surname (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Subjects (Subject)+>
        <!ELEMENT Subject (Description, Progress) >
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Progress (#PCDATA)>
        ]>
<Students>
    <Student>
        <Name>Ivan</Name>
        <Surname>Ivanov</Surname>
        <Email>ivan@ivan.it</Email>
        <Subjects>
            <Subject>
                <Description>Automation</Description>
                <Progress>9</Progress>
            </Subject>
            <Subject>
                <Description>Java_Programming</Description>
                <Progress>9</Progress>
            </Subject>
        </Subjects>
    </Student>
    <Student>
        <Name>Peter</Name>
        <Surname>Petrov</Surname>
        <Email>pit@ivan.it</Email>
        <Subjects>
            <Subject>
                <Description>Automation</Description>
                <Progress>8</Progress>
            </Subject>
            <Subject>
                <Description>Java_Programming</Description>
                <Progress>6</Progress>
            </Subject>
        </Subjects>
    </Student>
</Students>