<?xml version="1.0" encoding="UTF-8" standaolne="yes"?>
<!DOCTYPE Persons[
        <!ELEMENT Persons (Person)+>
        <!ELEMENT Person (Email, Nickname, Password, Ads)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Ads (Ad)+>
        <!ELEMENT Ad (Descriprion, Adress, Floor, Floors, Square, Price)>
        <!ELEMENT Descriprion (#PCDATA)>
        <!ELEMENT Adress (#PCDATA)>
        <!ELEMENT Floor (#PCDATA)>
        <!ELEMENT Floors (#PCDATA)>
        <!ELEMENT Square (#PCDATA)>
        <!ELEMENT Price (#PCDATA) >
        >
        <Persons>
        <Person>
        <Email>asde@sfdfd.it</Email>
        <Nickname>asdd123</Nickname>
        <Password>qwerty</Password>
        <Ads>
        <Ad>
        <Descriprion>Отличный вариант</Descriprion>
        <Adress>Минск Ленина 29 кв. 5</Adress>
        <Floor>3</Floor>
        <Floors>5</Floors>
        <Square>49.0</Square>
        <Price>99999</Price>
        </Ad>
        </Ads>
        </Person>
        </Persons>